# Generated by Django 2.2.7 on 2019-11-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity_expense',
            name='cost',
        ),
    ]
