# Generated by Django 2.2.7 on 2019-11-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_remove_electricity_expense_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity_expense',
            name='expense',
            field=models.FloatField(default=0.0),
        ),
    ]
