# Generated by Django 2.2.7 on 2019-11-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0004_auto_20191123_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity_expense',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='electricity_expense',
            name='units',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
