# Generated by Django 2.2.7 on 2019-11-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0005_auto_20191126_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity_expense',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
